### ISSUE TITLE
Design Docs Feedback: Backend & Frontend Routes

### ISSUE THREAD

**Issue by RosemaryGonzaga** [MannanK/Superflix#3]
DESIGN DOCS FEEDBACK - Backend Routes:

1. Lists
   - [x] Based on schema feedback, you shouldn’t need a route to fetch a single list.
2. Lists_media
   - [x] I would make this first route, which fetches all media for a given list, a nested route. It should be nested under the user_id: `GET /api/users/:user_id/media` (or, later under profile_id: `GET /api/profiles/:profile_id/media` ).
   - [x] As it stands, your current `POST` and `DELETE` routes will work using the `current_user` helper method defined by your application controller. However, once you implement profiles, it won’t be enough to rely on the user_id. You will need to associate the video with a particular profile via the profile_id. Consider whether you want to include both foreign keys via two wildcards in the route, or form data.
3. Genres
   - [x] Add `GET /api/genres` to fetch all genres (which will be handy for the landing page and / or search feature)

DESIGN DOCS FEEDBACK - Frontend Routes:

- No suggested changes

**Comment by MannanK** [comment]
Got it, thanks for the feedback!
