### ISSUE TITLE
User Authentication Feedback

### ISSUE THREAD

**Issue by RosemaryGonzaga** [MannanK/Superflix#5]
Hey Mannan, great work on user auth, it works and looks very similarly to Netflix! (I also love that you got your dropdown working so smoothly.) A few comments below - let me know if you have questions!

### Errors:
   - Error rendering is working wonderfully! You should show off your chops even more by making those errors more dynamic - and changing in them response to what the user types into the fields. 
      - [x] Password validation: The error message should go away once the user types in the minimum required number of characters.
      - [x] Email validation: Technically the error message is different if the input is blank vs if it has some text that isn't recognized as an email address. I think you can just keep the error message the same in both scenarios but adjust the message to be applicable in both cases: "Please enter a valid email."

### Styling:
   - [x] The default styling for inputs is to have a blue outline when focused. This is not the case for Netflix. Remove blue outline from inputs (email and password inputs, as well as the buttons)
   - [x] Splash page: Add a black footer (similar opacity to your actual session form). Even though you won't have the same links as Netflix, you can later use that footer to house your personal links (github, linkedIn, portfolio site).
   - [x] The orange border that appears when errors are showing should be curved instead of straight. Instead of using a border on the `errors` span, apply a border-bottom to the inputs themselves.
   - [x] Add a favicon (the little icon that appears on your webpage tab to the left of your webpage name). 
      - To do this, include your favicon image in your “assets/images” folder, and then add this line to your application.html.erb:
      `<%= favicon_link_tag asset_path('filename.ext') %>.` 
      You can use any image you want as your icon, or you can generate your own. Here's a handy icon generator: https://favicon.io/favicon-generator/.

**Comment by MannanK** [comment]
Thanks!
